version: '3'
services:
  ng-rolodex:
    image: itzymin/ng-rolodex:${IMAGE_VERSION}-local
    depends_on:
      - pg
      - redis
    command: ["npm", "run", "start"]
    container_name: ng-rolodex
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
      - "4200:4200"
    networks:
      - my-app-network
  pg:
    image: postgres:10.0-alpine
    env_file: .env
    volumes: 
      - pg-data-volume:/var/lib/postgresql/data
    ports: 
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - my-app-network
  redis:
    image: redis:4.0-alpine
    env_file: .env
    volumes:
      - redis-data-volume:/data
    ports:
      - '${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}'
    networks:
      - my-app-network

volumes: 
  pg-data-volume:
  redis-data-volume:
networks:
  my-app-network: